@url=https://5vw2zta5p4.execute-api.us-east-1.amazonaws.com/prod/


GET {{url}}/employees?id=0495ef28-4e08-4b31-bb12-d6ac3243f03e
### GET method


POST {{url}}/employees
Content-Type: application/json

{
    "name": "John Doe",
    "age": 30
}
### POST method