name: python cdk deploy

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: install web app dependencies
      working-directory: ./web
      run: npm ci # clean install

    - name: build web app
      working-directory: ./web
      run: npm run build

    - name: install AWS CDK
      run: sudo npm install -g aws-cdk

    - name: install deployment dependencies
      working-directory: ./py-web
      run: pip3 install -r requirements.txt

    - name: cdk synth
      working-directory: ./py-web
      run: cdk synth

    - name: cdk deploy
      working-directory: ./py-web
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: cdk deploy